ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
# FROM docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
FROM elastic/kibana:${ELASTIC_VERSION}
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
